# NOTICE: This code is provided solely for the purpose of completing a hiring assessment.
# Any reuse, distribution, or incorporation into other projects (commercial or non-commercial)
# is strictly prohibited and gives legal ground if abused.

# Manages the lifecycle of Vagrant VMs: up, provision, ssh-config export, and inventory generation.
#
# Design notes:
# - `vagrant up` is idempotent for already-running VMs (no-op if all machines are up).
# - The trigger on vagrantfile_sha256 ensures Terraform re-runs provisioning on config changes.
# - SSH ports are dynamically assigned by vagrant-qemu (QEMU NAT), so the Ansible inventory
#   is generated by parsing `vagrant ssh-config` output rather than using static IPs.
# - The destroy provisioner runs `vagrant destroy -f` on `terraform destroy`.
# LLM note: null_resource trigger pattern, destroy provisioner, and ssh-config parsing
#            designed with Claude Code assistance.

resource "null_resource" "vagrant_up" {
  # Store vagrantfile_dir in triggers so it is accessible via self.triggers during destroy.
  # Destroy-time provisioners cannot reference variables — only self attributes.
  triggers = {
    vagrantfile_hash = var.vagrantfile_sha256
    vagrantfile_dir  = var.vagrantfile_dir
  }

  provisioner "local-exec" {
    command     = <<-EOT
      set -e
      echo "[vagrant-lifecycle] Starting vagrant up in ${var.vagrantfile_dir}"
      cd "${var.vagrantfile_dir}"
      vagrant up --no-tty 2>&1
      echo "[vagrant-lifecycle] vagrant up completed"
    EOT
    interpreter = ["bash", "-c"]
  }

  provisioner "local-exec" {
    when        = destroy
    command     = <<-EOT
      echo "[vagrant-lifecycle] Destroying VMs in ${self.triggers["vagrantfile_dir"]}"
      cd "${self.triggers["vagrantfile_dir"]}" && vagrant destroy -f 2>&1 || true
    EOT
    interpreter = ["bash", "-c"]
  }
}

# Export SSH config and generate the Ansible inventory from it.
# vagrant-qemu assigns dynamic host ports for SSH (QEMU NAT); we must read them after `vagrant up`.
resource "null_resource" "vagrant_inventory" {
  depends_on = [null_resource.vagrant_up]

  triggers = {
    vagrantfile_hash = var.vagrantfile_sha256
  }

  provisioner "local-exec" {
    command     = <<-EOT
      set -e
      echo "[vagrant-lifecycle] Exporting SSH config and generating Ansible inventory"
      cd "${var.vagrantfile_dir}"

      # Write vagrant ssh-config to a known path for reference
      vagrant ssh-config > "${var.vagrantfile_dir}/.vagrant/ssh-config"

      # Parse ssh-config and generate Ansible inventory using Python 3
      # (Python 3 is a required prerequisite documented in README)
      python3 - "${var.vagrantfile_dir}/.vagrant/ssh-config" \
                "${var.ansible_inventory_dir}/${var.cluster_name}.ini" \
                "${var.cluster_name}" << 'PYEOF'
import sys, re

ssh_config_path, inventory_path, cluster_name = sys.argv[1], sys.argv[2], sys.argv[3]

hosts = {}
current = None
with open(ssh_config_path) as f:
    for line in f:
        line = line.strip()
        m = re.match(r'^Host\s+(\S+)$', line)
        if m:
            current = m.group(1)
            hosts[current] = {}
            continue
        if current:
            m = re.match(r'^(\S+)\s+(.+)$', line)
            if m:
                hosts[current][m.group(1)] = m.group(2).strip('"')

cp_hosts     = {k: v for k, v in hosts.items() if '-cp-'     in k}
worker_hosts = {k: v for k, v in hosts.items() if '-worker-' in k}

def host_line(name, info):
    return (
        f"{name}"
        f" ansible_host={info.get('HostName', '127.0.0.1')}"
        f" ansible_port={info.get('Port', '22')}"
        f" ansible_user={info.get('User', 'vagrant')}"
        f" ansible_ssh_private_key_file={info.get('IdentityFile', '')}"
        f" ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
    )

import os
os.makedirs(os.path.dirname(inventory_path), exist_ok=True)
with open(inventory_path, 'w') as f:
    f.write("# NOTICE: This code is provided solely for the purpose of completing a hiring assessment.\n")
    f.write("# Generated by Terraform vagrant-lifecycle — do not edit manually.\n\n")
    f.write("[control_plane]\n")
    for name, info in sorted(cp_hosts.items()):
        f.write(host_line(name, info) + "\n")
    f.write("\n[workers]\n")
    for name, info in sorted(worker_hosts.items()):
        f.write(host_line(name, info) + "\n")
    f.write("\n[k3s_cluster:children]\ncontrol_plane\nworkers\n")
    f.write(f"\n[all:vars]\ncluster_name={cluster_name}\n")

print(f"[vagrant-lifecycle] Inventory written to {inventory_path}")
PYEOF
    EOT
    interpreter = ["bash", "-c"]
  }
}
