# NOTICE: This code is provided solely for the purpose of completing a hiring assessment.
# Any reuse, distribution, or incorporation into other projects (commercial or non-commercial)
# is strictly prohibited and gives legal ground if abused.

variable "cluster_name" {
  description = "Cluster name — used to label the inventory file"
  type        = string
}

variable "node_inventory" {
  description = "Map of node name => { ip, role, cpus, memory_mb } from vm-cluster module"
  type = map(object({
    ip        = string
    role      = string
    cpus      = number
    memory_mb = number
  }))
}

variable "ssh_config_path" {
  description = "Path to the vagrant ssh-config file generated by vagrant-lifecycle"
  type        = string
}

variable "ansible_inventory_dir" {
  description = "Directory where the Ansible inventory file will be written"
  type        = string
}

variable "ssh_private_key_path" {
  description = "Path to the private SSH key used to connect to VMs"
  type        = string
  default     = "~/.ssh/id_rsa"
}

variable "ansible_user" {
  description = "SSH user for Ansible connections"
  type        = string
  default     = "vagrant"
}
