# NOTICE: This code is provided solely for the purpose of completing a hiring assessment.
# Any reuse, distribution, or incorporation into other projects (commercial or non-commercial)
# is strictly prohibited and gives legal ground if abused.
---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
