# NOTICE: This code is provided solely for the purpose of completing a hiring assessment.
# Any reuse, distribution, or incorporation into other projects (commercial or non-commercial)
# is strictly prohibited and gives legal ground if abused.

# Generated by Terraform — do not edit manually.
# Cluster: ${cluster_name}

[control_plane]
%{ for name, node in control_plane_nodes ~}
${name} ansible_host=${node.ip} ansible_user=${ansible_user} ansible_ssh_private_key_file=${ssh_private_key_path} ansible_ssh_common_args='-o StrictHostKeyChecking=no'
%{ endfor ~}

[workers]
%{ for name, node in worker_nodes ~}
${name} ansible_host=${node.ip} ansible_user=${ansible_user} ansible_ssh_private_key_file=${ssh_private_key_path} ansible_ssh_common_args='-o StrictHostKeyChecking=no'
%{ endfor ~}

[k3s_cluster:children]
control_plane
workers

[all:vars]
cluster_name=${cluster_name}
