# NOTICE: This code is provided solely for the purpose of completing a hiring assessment.
# Any reuse, distribution, or incorporation into other projects (commercial or non-commercial)
# is strictly prohibited and gives legal ground if abused.

# Generated by Terraform — do not edit manually.
# Source: terraform/modules/vm-cluster/templates/Vagrantfile.tpl
# LLM note: structure and variable interpolation designed with Claude Code assistance.
#
# Provider: vagrant-qemu — required for Apple Silicon (ARM64) hosts.
# VirtualBox cannot run x86 VMs on ARM; QEMU uses Apple's native Hypervisor framework (HVF).
#
# Networking:
#   - Interface 0 (NAT): QEMU user-mode, used for SSH access from host and internet.
#   - Interface 1 (cluster): QEMU socket multicast (localaddr=127.0.0.1).
#     localaddr pins the socket to loopback so macOS routes between QEMU processes.
#     All nodes join the same group; static IPs configured via shell provisioner.

Vagrant.configure("2") do |config|
  config.vm.box = "${box_name}"
%{ if box_version != "" ~}
  config.vm.box_version = "${box_version}"
%{ endif ~}

  # Disable default /vagrant synced folder for security
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Inject operator SSH public key into all nodes
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("${ssh_public_key_path}").first.strip
    s.inline = <<-SHELL
      mkdir -p /home/vagrant/.ssh
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
    SHELL
  end

%{ for node in nodes ~}
  config.vm.define "${node.name}" do |n|
    n.vm.hostname = "${node.name}"

    n.vm.provider "qemu" do |qemu|
      qemu.arch       = "aarch64"
      qemu.machine    = "virt,accel=hvf,highmem=off"
      qemu.cpu        = "host"
      qemu.net_device = "virtio-net-pci"
      qemu.memory     = "${node.memory_mb}"
      qemu.smp        = "${node.cpus}"
      # Unique SSH port per node — avoids host port collisions when multiple VMs run.
      qemu.ssh_port   = "${node.ssh_port}"
      # Second NIC: QEMU socket multicast with localaddr=127.0.0.1.
      # localaddr pins the multicast socket to the loopback interface so macOS routes
      # packets between QEMU processes on the same host rather than out via en0.
      # All nodes in the cluster join the same multicast group on the same host port.
      #
      # Control-plane nodes additionally expose port 6443 via a hostfwd user NIC so that
      # worker nodes can reach the k3s API server at 10.0.2.2:6443 (QEMU SLIRP gateway).
%{ if node.role == "control-plane" ~}
      qemu.extra_qemu_args = [
        "-netdev", "socket,id=clusternet,mcast=230.0.0.1:${mcast_port},localaddr=127.0.0.1",
        "-device", "virtio-net-pci,netdev=clusternet",
        "-netdev", "user,id=k8sfwd,hostfwd=tcp:0.0.0.0:6443-:6443",
        "-device", "virtio-net-pci,netdev=k8sfwd"
      ]
%{ else ~}
      qemu.extra_qemu_args = [
        "-netdev", "socket,id=clusternet,mcast=230.0.0.1:${mcast_port},localaddr=127.0.0.1",
        "-device", "virtio-net-pci,netdev=clusternet"
      ]
%{ endif ~}
    end

    # Configure static cluster IP on the secondary interface (multicast network).
    # The primary interface (NAT) is detected via the default route; everything else is cluster.
    n.vm.provision "shell", inline: <<-SHELL
      set -e
      sleep 2

      PRIMARY_IF=$(ip route show default 2>/dev/null | awk '/default/{print $5; exit}')
      CLUSTER_IF=$(ip -o link show | awk -F': ' '{print $2}' | grep -Ev "^(lo|$${PRIMARY_IF})" | grep -v '@' | head -1)

      if [ -z "$CLUSTER_IF" ]; then
        echo "WARNING: No secondary cluster interface detected — skipping cluster IP config"
      else
        echo "Configuring cluster interface: $CLUSTER_IF with IP ${node.ip}/24"
        ip addr flush dev "$CLUSTER_IF" 2>/dev/null || true
        ip addr add ${node.ip}/24 dev "$CLUSTER_IF" || true
        ip link set "$CLUSTER_IF" up

        mkdir -p /etc/netplan
        cat > /etc/netplan/99-cluster.yaml << NETPLAN
network:
  version: 2
  ethernets:
    $CLUSTER_IF:
      addresses:
        - ${node.ip}/24
NETPLAN
        netplan apply 2>/dev/null || true
      fi

      echo "vagrant-ready" > /etc/vagrant-bootstrap-marker
      echo "Node ${node.name} ready | Cluster IP: ${node.ip} | Role: ${node.role}"
    SHELL
  end

%{ endfor ~}
end
